config/routes.rb
Rails.application.routes.draw do
  resources :postal_codes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/postal_code.rb
class PostalCode < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/postal_codes_controller.rb
class PostalCodesController < ApplicationController
  before_action :set_postal_code, only: %i[ show edit update destroy ]

  # GET /postal_codes or /postal_codes.json
  def index
    @postal_codes = PostalCode.all
  end

  # GET /postal_codes/1 or /postal_codes/1.json
  def show
  end

  # GET /postal_codes/new
  def new
    @postal_code = PostalCode.new
  end

  # GET /postal_codes/1/edit
  def edit
  end

  # POST /postal_codes or /postal_codes.json
  def create
    @postal_code = PostalCode.new(postal_code_params)

    respond_to do |format|
      if @postal_code.save
        format.html { redirect_to postal_code_url(@postal_code), notice: "Postal code was successfully created." }
        format.json { render :show, status: :created, location: @postal_code }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @postal_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postal_codes/1 or /postal_codes/1.json
  def update
    respond_to do |format|
      if @postal_code.update(postal_code_params)
        format.html { redirect_to postal_code_url(@postal_code), notice: "Postal code was successfully updated." }
        format.json { render :show, status: :ok, location: @postal_code }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @postal_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postal_codes/1 or /postal_codes/1.json
  def destroy
    @postal_code.destroy

    respond_to do |format|
      format.html { redirect_to postal_codes_url, notice: "Postal code was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postal_code
      @postal_code = PostalCode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def postal_code_params
      params.require(:postal_code).permit(:postal_code, :state, :country, :longitude, :latitude, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/postal_codes_helper.rb
module PostalCodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdwerxInternshipExercise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/postal_codes/_form.html.erb
<%= form_with(model: postal_code) do |form| %>
  <% if postal_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(postal_code.errors.count, "error") %> prohibited this postal_code from being saved:</h2>

      <ul>
        <% postal_code.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.number_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/postal_codes/edit.html.erb
<h1>Editing Postal Code</h1>

<%= render 'form', postal_code: @postal_code %>

<%= link_to 'Show', @postal_code %> |
<%= link_to 'Back', postal_codes_path %>

app/views/postal_codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Postal Codes</h1>

<table>
  <thead>
    <tr>
      <th>Postal code</th>
      <th>State</th>
      <th>Country</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postal_codes.each do |postal_code| %>
      <tr>
        <td><%= postal_code.postal_code %></td>
        <td><%= postal_code.state %></td>
        <td><%= postal_code.country %></td>
        <td><%= postal_code.longitude %></td>
        <td><%= postal_code.latitude %></td>
        <td><%= postal_code.city %></td>
        <td><%= link_to 'Show', postal_code %></td>
        <td><%= link_to 'Edit', edit_postal_code_path(postal_code) %></td>
        <td><%= link_to 'Destroy', postal_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Postal Code', new_postal_code_path %>

app/views/postal_codes/new.html.erb
<h1>New Postal Code</h1>

<%= react_component("PostalCodeForm", { token: form_authenticity_token }) %>

<%= link_to 'Back', postal_codes_path %>

app/views/postal_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Postal code:</strong>
  <%= @postal_code.postal_code %>
</p>

<p>
  <strong>State:</strong>
  <%= @postal_code.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @postal_code.country %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @postal_code.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @postal_code.latitude %>
</p>

<p>
  <strong>City:</strong>
  <%= @postal_code.city %>
</p>

<%= link_to 'Edit', edit_postal_code_path(@postal_code) %> |
<%= link_to 'Back', postal_codes_path %>